#pragma once

#include <opencv2/opencv.hpp>

// Include the generated C++ header for Rust FFI
#include "bridge.rs.h" // generated by cxx-build

namespace from_rust
{
    inline cv::Mat resize_image(const cv::Mat &img, int width, int height)
    {
        // Call the Rust function via the C++ bridge
        auto resized_ptr = _resize_image_rust(img, width, height);
        if (!resized_ptr || resized_ptr->empty())
        {
            throw_error("resize_image_with_rust: resized image is empty");
        }
        return *resized_ptr;
    }
};
